name: CD - Release
on:
  push:
    tags: [ "v*.*.*" ]

env:
  IMAGE_NAME: sanjay1233/rubixe

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Version
        id: v
        run: echo "ver=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ steps.v.outputs.ver }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
