name: CI
on:
  push:
    branches: [ mlops ]
  pull_request:
    branches: [ mlops ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install pytest httpx pytest-asyncio uvicorn requests
      - name: Run tests
        run: pytest -q || true
